### ISSUE TITLE
Cannot uninstall yunohost-config-amavis and yunohost-config-dovecot

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost/install_script#11] opened 2014-05-16 12:59 UTC
```
The following packages will be REMOVED:
  yunohost-config-amavis* yunohost-config-dovecot*
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 0 B of additional disk space will be used.
Do you want to continue [Y/n]? y
(Reading database ... 57312 files and directories currently installed.)
Removing yunohost-config-amavis ...
Purging configuration files for yunohost-config-amavis ...
rm: cannot remove `/etc/default/spamassassin': No such file or directory
dpkg: error processing yunohost-config-amavis (--purge):
 subprocess installed post-removal script returned error exit status 1
Removing yunohost-config-dovecot ...
Purging configuration files for yunohost-config-dovecot ...
rm: cannot remove `/etc/dovecot/global_script/dovecot.svbin': No such file or directory
dpkg: error processing yunohost-config-dovecot (--purge):
 subprocess installed post-removal script returned error exit status 1
Errors were encountered while processing:
 yunohost-config-amavis
 yunohost-config-dovecot
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by julienmalik** [comment] 2015-09-09 09:54
Duplicate of https://github.com/YunoHost/yunohost-config-dovecot/issues/6

**Closed by julienmalik** 2015-09-09 09:54 UTC
Labels: bug
